# Generated by Django 5.1.1 on 2024-10-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('xp_reward', models.IntegerField(default=10)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
